-- ============================================================================
-- Query Fragment: WHERE para Buscar Estabelecimento por Código
-- ============================================================================
-- Descrição:
--   Fragmento SQL contendo apenas a cláusula WHERE para buscar um
--   estabelecimento específico pelo seu código.
--
-- Uso:
--   Este arquivo é COMBINADO com projection.sql na execução:
--   Query Final = projection.sql + get-by-codigo.sql
--
-- Parâmetros:
--   ? (varchar) - Código do estabelecimento a ser buscado (parâmetro ODBC)
--
-- Utilizado por:
--   - estabelecimento/dadosCadastrais/informacoesGerais/repository.ts :: getEstabelecimentoMaster()
--
-- Performance:
--   - WHERE executado no Progress/OpenEdge (banco MULT)
--   - Retorna no máximo 1 registro
--   - Usa índice primário da tabela estabelec
--
-- Exemplo de valor:
--   ? = '01'     → Busca estabelecimento com código '01'
--   ? = 'MATRIZ' → Busca estabelecimento com código 'MATRIZ'
--
-- Última atualização: 2025-10-26
-- Criado para suportar composição modular
-- ============================================================================

WHERE estabelec."cod-estabel" = ?
