SELECT  i."it-codigo"                     as itemCodigo
      , i."desc-item"                     as itemDescricao
      , iue."cod-estabel"                 as estabCodigo
      , iue."deposito-pad"                as depositoPadrao
      , iue."cod-localiz"                 as localizacao
      , iue."cod-obsoleto"                as situacao
      , p."cd-planejado"                  as planejadorCodigo
      , p.nome                            as planejadorNome
      , lp."nr-linha"                     as linhaProducaoCodigo
      , lp.descricao                      as linhaProducaoNome
      , iue."cap-est-fabr"                as capacidadeEstoque
      , iue."log-consid-aloc-ativid"      as consideraAlocAtividades
      , iue."log-programac-sfc"           as programaAlocAtividades
      , iue."val-overlap"                 as percentualOverlap
      , iue."reporte-mob"                 as reportaMOB
      , iue."reporte-ggf"                 as reportaGGF
      , iue."sit-aloc"                    as tipoAlocacao
      , iue."tipo-requis"                 as tipoRequisicao
      , iue."ind-lista-csp"               as processoCustos
      , iue."rep-prod"                    as reporteProducao
      , iue."ind-refugo"                  as tratamentoRefugo
      , iue."log-control-estoq-refugo"    as controlaEstoque
      , iue."log-refugo-preco-fisc"       as precoFiscal
      , ir."it-codigo"                    as refugoItemCodigo
      , ir."desc-item"                    as refugoItemDescricao
      , iue."val-relac-refugo-item"       as refugoRelacaoItem
      , iue."fator-refugo"                as refugoFator
      , iue."quant-perda"                 as refugoPerda
      , iue.politica                      as politica
      , iue.demanda                       as demanda
      , iue."lote-multipl"                as loteMultiplo
      , iue."lote-minimo"                 as loteMinimo
      , iue."lote-economi"                as loteEconomico
      , iue."periodo-fixo"                as periodoFixo
      , iue."pto-repos"                   as pontoReposicao
      , iue."tipo-est-seg"                as estoqueSegurancaTipo
      , iue."quant-segur"                 as estoqueSegurancaQtd
      , iue."tempo-segur"                 as estoqueSegurancaTempo
      , iue."conv-tempo-seg"              as estoqueSegurancaConvTempo
      , iue."classe-repro"                as classeReprogramacao
      , iue."emissao-ord"                 as emissaoOrdens
      , iue."div-ordem"                   as divisaoOrdens
      , iue.prioridade                    as prioridade
      , iue."res-int-comp"                as ressuprimentoComprasQuantidade
      , iue."res-for-comp"                as ressuprimentoComprasFornecedor
      , iue."res-cq-comp"                 as ressuprimentoComprasCQ
      , iue."ressup-fabri"                as ressuprimentoFabricaQuantidade
      , iue."res-cq-fabri"                as ressuprimentoFabricaCQ
      , iue."qt-min-res-fabr"             as ressuprimentoFabricaMinimo
      , iue."var-tempo-res-fabr"          as ressupFabVarTempo
      , iue."var-qtd-res-fabr"            as ressupFabVarQuantidade
  FROM  pub."item-uni-estab" iue
  INNER JOIN pub.item i
    ON  i."it-codigo" = iue."it-codigo"
  INNER JOIN pub.planejad p
    ON  p."cd-planejado" = iue."cd-planejado"
  INNER JOIN pub."lin-prod" lp
    ON  lp."nr-linha" = iue."nr-linha"
    AND lp."cod-estabel" = iue."cod-estabel"
  LEFT  OUTER JOIN pub.item ir
    ON  ir."it-codigo" = iue."cod-item-refugo"
  WHERE iue."it-codigo" = ?
  ORDER BY  iue."cod-estabel"